export const imageMasks = [
    {
        id: "none",
        name: "Sin máscara",
        class: "",
        category: "Básicas",
        //icon: () => <Square className="h-4 w-4" />,
    },
    {
        id: "circle",
        name: "Círculo",
        class: "rounded-full",
        category: "Básicas",
        //icon: () => <Circle className="h-4 w-4" />,
    },
    {
        id: "rounded",
        name: "Redondeado",
        class: "rounded-xl",
        category: "Básicas",
        //icon: () => <Square className="h-4 w-4 rounded-md" />,
    },
    {
        id: "square",
        name: "Cuadrado",
        class: "",
        category: "Básicas",
        //icon: () => <Square className="h-4 w-4" />,
    },
    {
        id: "heart",
        name: "Corazón",
        class: "mask-heart",
        category: "Formas",
        //icon: () => <Heart className="h-4 w-4" />,
    },
    {
        id: "star",
        name: "Estrella",
        class: "mask-star-2",
        category: "Formas",
        //icon: () => <Star className="h-4 w-4" />,
    },
    {
        id: "hexagon",
        name: "Hexágono",
        class: "mask-hexagon",
        category: "Formas",
        //icon: () => <Hexagon className="h-4 w-4" />,
    },
    {
        id: "triangle",
        name: "Triángulo",
        class: "mask-triangle",
        category: "Formas",
        //icon: () => <div className="w-4 h-4 bg-current clip-triangle" />,
    },
    {
        id: "diamond",
        name: "Diamante",
        class: "mask-diamond",
        category: "Formas",
        //icon: () => <Diamond className="h-4 w-4" />,
    },
    {
        id: "polaroid",
        name: "Polaroid",
        class: "mask-polaroid",
        category: "Fotográficos",
        //icon: () => <Film className="h-4 w-4" />,
    },
    {
        id: "vintage",
        name: "Vintage",
        class: "mask-vintage",
        category: "Fotográficos",
        //icon: () => <Feather className="h-4 w-4" />,
    },
    {
        id: "wave",
        name: "Onda",
        class: "mask-wave",
        category: "Fotográficos",
        //icon: () => <Zap className="h-4 w-4" />,
    },
    {
        id: "diagonal",
        name: "Diagonal",
        class: "mask-diagonal",
        category: "Fotográficos",
        //icon: () => <div className="w-4 h-4 bg-current clip-diagonal" />,
    },
    {
        id: "frame",
        name: "Marco",
        class: "mask-frame",
        category: "Fotográficos",
        //icon: () => <Square className="h-4 w-4" />,
    },
    {
        id: "leaf",
        name: "Hoja",
        class: "mask-leaf",
        category: "Creativas",
        //icon: () => <Feather className="h-4 w-4" />,
    },
    {
        id: "cloud",
        name: "Nube",
        class: "mask-cloud",
        category: "Creativas",
        //icon: () => <Cloud className="h-4 w-4" />,
    },
    {
        id: "flower",
        name: "Flor",
        class: "mask-flower",
        category: "Creativas",
        //icon: () => <Flower className="h-4 w-4" />,
    },
    {
        id: "ornate",
        name: "Ornamento",
        class: "mask-ornate",
        category: "Creativas",
        //icon: () => <div className="w-4 h-4 bg-current clip-ornate" />,
    },
    {
        id: "blob1",
        name: "Mancha 1",
        class: "mask-blob1",
        category: "Creativas",
        //icon: () => <div className="w-4 h-4 bg-current rounded-full" />,
    },
    {
        id: "blob2",
        name: "Mancha 2",
        class: "mask-blob2",
        category: "Creativas",
        //icon: () => <div className="w-4 h-4 bg-current rounded-full" />,
    },
    {
        id: "blob3",
        name: "Mancha 3",
        class: "mask-blob3",
        category: "Creativas",
        //icon: () => <div className="w-4 h-4 bg-current rounded-full" />,
    },
    {
        id: "rounded-sm",
        name: "Redondeado pequeño",
        class: "rounded-md",
        category: "Básicas",
        //icon: () => <Square className="h-4 w-4 rounded-sm" />,
    },
    {
        id: "rounded-lg",
        name: "Redondeado grande",
        class: "rounded-2xl",
        category: "Básicas",
        //icon: () => <Square className="h-4 w-4 rounded-lg" />,
    },
    {
        id: "rounded-full",
        name: "Círculo perfecto",
        class: "rounded-full",
        category: "Básicas",
        //icon: () => <Circle className="h-4 w-4" />,
    },
    {
        id: "bevel",
        name: "Biselado",
        class: "mask-bevel",
        category: "Fotográficos",
        //icon: () => <Square className="h-4 w-4" />,
    },
    {
        id: "poster",
        name: "Poster",
        class: "mask-poster",
        category: "Fotográficos",
        //icon: () => <Film className="h-4 w-4" />,
    },
    {
        id: "badge",
        name: "Insignia",
        class: "mask-badge",
        category: "Formas",
        //icon: () => <div className="w-4 h-4 bg-current clip-badge" />,
    },
    {
        id: "speech",
        name: "Globo de texto",
        class: "mask-speech",
        category: "Formas",
        //icon: () => <div className="w-4 h-4 bg-current clip-speech" />,
    },
    {
        id: "burst",
        name: "Estallido",
        class: "mask-burst",
        category: "Formas",
        //icon: () => <Zap className="h-4 w-4" />,
    },
    {
        id: "rounded-rect",
        name: "Rectángulo redondeado",
        class: "mask-rounded-rect",
        category: "Básicas",
        //icon: () => <Square className="h-4 w-4 rounded-md" />,
    },
    {
        id: "inner-frame",
        name: "Marco interno",
        class: "mask-inner-frame",
        category: "Fotográficos",
        //icon: () => <Square className="h-4 w-4" />,
    },
];
